spring.application.name=lexguard

# DATABASE
spring.datasource.url=jdbc:mysql://localhost:3306/lexguard?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=12345
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# 🔐 JWT (ESSENCIAL)
jwt.secret=7klgDl+aHaEOQ5hRhqzIOM9X8m6YfUTXaOnpXHD2G3UIQHS9h/eqYxWvZ98DOlsdHCTQDxkWMjmqXOFC6pPsVw==
jwt.expiration-ms=86400000
jwt.refresh-expiration-ms=604800000

# ─── Super Admin (criado automaticamente na primeira inicialização) ───────────
app.superadmin.username=superadmin
app.superadmin.password=LexGuard@2025!
app.superadmin.nome=Super Administrador
app.superadmin.email=admin@lexguard.com.br